artifact_uri: file:///home/user/my_proj/research/mlflow/286043649673797089/109dad8ad9324ffc97ce91c91fee0d8a/artifacts
end_time: 1761504714850
entry_point_name: ''
experiment_id: '286043649673797089'
lifecycle_stage: active
run_id: 109dad8ad9324ffc97ce91c91fee0d8a
run_name: final_full_fit_production
run_uuid: 109dad8ad9324ffc97ce91c91fee0d8a
source_name: ''
source_type: 4
source_version: ''
start_time: 1761504710720
status: 3
tags: []
user_id: user
